### ISSUE TITLE
fdroid update

### ISSUE THREAD

**Issue by bingoxo** [simple-login/Simple-Login-Android#10]
can you please keep the fdroid versions up to date as well ? (1.4.1 in playstore vs 1.4 in f-droid)

**Comment by ntnhon** [comment]
Hi, indeed we are having an issue that cause SimpleLogin not being updated. I filed a report on F-droid  and apparently this will be fixed soon: https://gitlab.com/fdroid/fdroiddata/-/issues/2239#note_470446580

**Comment by bingoxo** [comment]
thanks for getting back so quickly , keep up the good work :D

**Comment by bingoxo** [comment]
I noticed the issue on gitlab closed , so i assume you have an eta when the update will be available ?

**Comment by ntnhon** [comment]
Hello, it is supposed to fixed the issue and update the app to 1.4.1 version but unfortunately nothing happened yet. I don't know if it needs a bit more time or I need to make an another release in order to trigger the update cycle. Not sure.

**Comment by ntnhon** [comment]
The update is finally live!
