### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [simple-login/Simple-Login-Android#11]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 1.4, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="439" alt="bug-fdroid_5" src="https://user-images.githubusercontent.com/18572115/103147709-e94f0780-4792-11eb-9432-fa5b440041ee.png">

**Comment by ntnhon** [comment]
Hello, the version text and "About us" button are always expected to be at the bottom of the screen. Actually I din't think about this extreme case when making this page. Maybe I will make the page scrollable to fix this.

**Comment by ntnhon** [comment]
And thank you for your support. I will have you updated when the issue is fixed.

**Comment by ntnhon** [comment]
Hi, sorry for the belated feedback. If you have a chance, please pull the source code, try it out and tell me if the problem persists.
