### ISSUE TITLE
Strange green corners on left side of app icon?

### ISSUE THREAD

**Issue by Pentaphon** [simple-login/Simple-Login-Android#13]
This is version 1.4.1 from the Play Store on an Android 9 device (Moto G7) using Nova Launcher. What is wrong with the icon?

![Screenshot_20201228-004107_1](https://user-images.githubusercontent.com/49374058/103201953-10e2c480-48a6-11eb-9767-007b2239c07e.png)

**Comment by ntnhon** [comment]
Hello, thank for reporting, I will investigate the issue and have you updated.

**Comment by ntnhon** [comment]
Hello, please update to the 1.7 version and tell me if the issue persists.

**Comment by Pentaphon** [comment]
I'm using the 1.7 version and the icon is fixed. Thanks.

**Comment by ntnhon** [comment]
Great! Feel free to report any issue that you happen to encounter :)
