### ISSUE TITLE
FDroid app Dark mode

### ISSUE THREAD

**Issue by eraserpencil** [simple-login/Simple-Login-Android#14]
Hi! Just found out about SimpleLogin. Yet to explore.

I'm using the FDroid app, found a display when the app uses the system's theme (I think). Apologies if this is not the right place for issues with FDroid apps.

Attached the picture.
![Screenshot_20210104-201944](https://user-images.githubusercontent.com/16631431/103534860-ad225200-4eca-11eb-8114-d7889352788d.jpg)

I'm using a One Plus 6 phone with Oxygen OS 10.3.7

**Comment by ntnhon** [comment]
Hello, you are absolutely at the right place and thank you for reporting the issue. I will have it fixed asap :)
