### ISSUE TITLE
Ability to change the account email address 

### ISSUE THREAD

**Issue by AnonymousSeal** [simple-login/Simple-Login-Android#15]
Hey,
so I wanted to change my account email address, because I want to link it to my main email (SimpleLogin has made the other email redundant) and i found that this is not yet possible.
I would really appreciate it if you could add ***the ability to change the account email address*** as a feature
Thanks :)

**Comment by ntnhon** [comment]
Hello, we have an open roadmap in which users can freely ask for features. I created a ticket for your request. Feel free to vote and suggest more.
https://trello.com/c/ZNxkP3cv/150-able-to-change-account-email-address
