### ISSUE TITLE
In Contact screen, rotating the screen makes the app ask for the local authentification

### ISSUE THREAD

**Issue by subiol** [simple-login/Simple-Login-Android#26]
In the Contact screen there is a bug when the phone screen rotates. It does not happen in the main screen and I have not noticed it happens in any other screen.

In this screen, the contact screen, when I rotate the phone and the screen rotates, it asks for the local authentification again when it should not. Even worse, after the authentification is passed, the app crashes and disappears. I have to launch it again and start over with what I was doing.

I am using the last version from F-Droid, v1.7 .

**Comment by ntnhon** [comment]
Thank you for reporting. I will have it fixed.
