### ISSUE TITLE
Allow to select emails from the phone contacts

### ISSUE THREAD

**Issue by subiol** [simple-login/Simple-Login-Android#27]
When pressing Send email to create a reverse alias, you should add the option to select an email from the phone contacts. It makes little sense having to have our contacts in two places.

**Comment by ntnhon** [comment]
Actually it's a good idea but we are a bit hesitant as SimpleLogin is a product for privacy minded folks. Such an access to contact list exposes serious privacy issue. Maybe we can have something in between by making it an option in Settings and users have to manually activate it if they want.

**Comment by subiol** [comment]
Well, there is certain amount of trust that users have to place on SimpleLogin, since you see who we send emails to and the contents. Plus on Android, users already have the option of allowing or blocking the app from accessing the contacts at system level, but yeah, including it as an option is ok too.

**Comment by ntnhon** [comment]
Hello, I kind of finished implementing this feature. You can play around with it while I do some tests before merging. The branch is https://github.com/simple-login/Simple-Login-Android/tree/enhancement_%2327

**Comment by subiol** [comment]
That was quick. Unfortunately I do not do Android development. I did some small thing years ago, but right now I do not have Android Studio installed, so I will have to wait for the release to see.
