### ISSUE TITLE
Force-closing

### ISSUE THREAD

**Issue by BeecherNetworks** [simple-login/Simple-Login-Android#3]
Updated yesterday, force-closing today. Samsung S10E dual SIM. Self-hosted. Let me know if you need any other info or data.

**Comment by ntnhon** [comment]
Hi, what error message do you see?

**Comment by BeecherNetworks** [comment]
It just force closes, no error. I'll try clearing cache and then data shortly.

![Screenshot_20200614-144007_SimpleLogin](https://user-images.githubusercontent.com/179583/84594892-ec188980-ae4c-11ea-8ce7-0ceefa506c20.png)

**Comment by BeecherNetworks** [comment]
Cleared cache, no go.

Cleared data, got back to login screen, changed API URL, started force closing again.

Reinstalled, can't get it to open at all.

**Comment by ntnhon** [comment]
If I make no mistake you are running the 1.4 version which makes calls to newer versions of endpoint but your SimpleLogin instance is not up to date. Can you please tell me which version of SimpleLogin you are running on?

**Comment by ntnhon** [comment]
In other words, make sure that the `GET /api/v2/aliases` returns an array of `mailboxes` because the 1.4 version starts to take into account mailboxes.

**Comment by BeecherNetworks** [comment]
That would make sense, I'm on version 3.1.1 on the server side. It may also account for the TZ errors I'm having with the web app, I didn't update because there were no release notes, didn't think it would be significant.

Upgrading didn't work for me, I get the error below, should I open this as a new ticket under the web app? It's not critical, I don't really use the app a whole lot yet.

```
root@yy:~$ sudo docker run --rm \
>     --name sl-migration \
>     -v $(pwd)/sl:/sl \
>     -v $(pwd)/dkim.key:/dkim.key \
>     -v $(pwd)/dkim.pub.key:/dkim.pub.key \
>     -v $(pwd)/simplelogin.env:/code/.env \
>     --network="sl-network" \
>     simplelogin/app:3.2.0 flask db upgrade
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 418, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 386, in load_app
    raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 236, in locate_app
    __import__(module_name)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 15, in <module>
    from app import paddle_utils
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 39, in <module>
    URL = os.environ["URL"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'URL'
```

**Comment by ntnhon** [comment]
Maybe @nguyenkims can help.

**Comment by nguyenkims** [comment]
@BeecherNetworks hey it seems that your config file `$(pwd)/simplelogin.env` doesn't have the `URL` parameter defined.

For 3.2.0, you can find its release notes in the CHANGELOG https://github.com/simple-login/app/blob/master/CHANGELOG

**Comment by BeecherNetworks** [comment]
Definitely does. It's not in quotes, but it isn't in the example either. Is spacing important in the env file?

```
URL = http://yy.ie
EMAIL_DOMAIN = yy.ie
SUPPORT_NAME = "YY.ie"
SUPPORT_EMAIL = yy@yy.ie
EMAIL_SERVERS_WITH_PRIORITY = [(10, "yy.ie.")]
DISABLE_ALIAS_SUFFIX = 1
DISABLE_REGISTRATION = 1
DKIM_PRIVATE_KEY_PATH = /dkim.key
DKIM_PUBLIC_KEY_PATH = /dkim.pub.key
```

**Comment by nguyenkims** [comment]
@BeecherNetworks this param is the first param in the example config https://github.com/simple-login/app/blob/9abfa3e98cd93c7e61685a53b7324610fba5940c/example.env#L2 and in the self-hosted instruction https://github.com/simple-login/app/blob/c847d205b66b6c91e9565a556da8ea40975ba60f/README.md#L440

Can you paste the output of the below command here? Make sure to remove the `DB_URI` and `FLASK_SECRET` ones.

```
cat $(pwd)/simplelogin.env
```

**Comment by BeecherNetworks** [comment]
I did in my last message? It's not complete, I cut it off at the db URL as it contains passwords.

**Comment by nguyenkims** [comment]
@BeecherNetworks  ah sorry, I didn't notice that this is your config file. The URL is indeed present 🤔. Space is not important in this config file. If your domain contains a special character you can put it in quotes`""` to be 100% sure. A probably dummy question: do you run the command from the directory where `simplelogin.env` is present?

**Comment by BeecherNetworks** [comment]
Thanks. I've hardcoded the paths, here's the docker runs:

```
docker run --detach --restart unless-stopped \
	--name sl-db \
	-e POSTGRES_PASSWORD=[password] \
	-e POSTGRES_USER=simplelogin \
	-e POSTGRES_DB=simplelogin \
	-p 127.0.0.1:5432:5432 \
	-v /simplelogin/data:/var/lib/postgresql/data \
	--network="sl-network" \
	postgres:12.1

docker run --detach --restart unless-stopped \
	--name sl-app \
	-v /simplelogin:/sl \
	-v /simplelogin/simplelogin.env:/code/.env \
	-v /simplelogin/dkim.key:/dkim.key \
	-v /simplelogin/dkim.pub.key:/dkim.pub.key \
	-p 127.0.0.1:7777:7777 \
	--restart unless-stopped \
	--network="sl-network" \
	simplelogin/app:3.1.1

docker run --detach --restart unless-stopped \
	--name sl-email \
	-v /simplelogin:/sl \
	-v /simplelogin/simplelogin.env:/code/.env \
	-v /simplelogin/dkim.key:/dkim.key \
	-v /simplelogin/dkim.pub.key:/dkim.pub.key \
	-p 127.0.0.1:20381:20381 \
	--restart unless-stopped \
	--network="sl-network" \
	simplelogin/app:3.1.1 python email_handler.py
```

**Comment by nguyenkims** [comment]
As the upgrade guide is based on the paths set in the self-host guide, if you use custom paths, you'd need to change the default paths when upgrading.

From what I see you need to replace all the mounts by your custom paths, so instead of 

```
-v $(pwd)/sl:/sl \
-v $(pwd)/simplelogin.env:/code/.env \
-v $(pwd)/dkim.key:/dkim.key \
-v $(pwd)/dkim.pub.key:/dkim.pub.key \
```

you'd need to use

```
-v /simplelogin:/sl \
-v /simplelogin/simplelogin.env:/code/.env \
-v /simplelogin/dkim.key:/dkim.key \
-v /simplelogin/dkim.pub.key:/dkim.pub.key \
```

**Comment by BeecherNetworks** [comment]
@nguyenkims I had done that but I missed one, apologies. All good now.
