### ISSUE TITLE
Unknown Error: Timeout

### ISSUE THREAD

**Issue by IzumiSena** [simple-login/Simple-Login-Android#38]
I am facing error Everytime i open SimpleLogin app in Android it's showing this error

![Screenshot_20210319-154750](https://user-images.githubusercontent.com/61591769/111910118-486aa280-8a8a-11eb-949a-2576084afe67.png)

I downloaded this app from playstore! 
Android 10 running
App updated to latest version! 1.8 
I am facing this error whenever i open SimpleLogin app! Others all functionality working perfectly Like setting or mailbox everything ok! And when it comes to main alias page even if i refresh multiple time it's showing timeout error! So hope you guys can fix it!

**Comment by nguyenkims** [comment]
@IzumiSena I wonder if you happen to have a firewall currently running on your Wifi network or on your phone? Some other users have reported some firewall programs block SimpleLogin request.

**Comment by nguyenkims** [comment]
@IzumiSena another thing, could you please try the SimpleLogin web version on your phone and let us know if the timeout issue happens there as well? Thanks!

**Comment by IzumiSena** [comment]
> @IzumiSena another thing, could you please try the SimpleLogin web version on your phone and let us know if the timeout issue happens there as well? Thanks!

Yes i can do everything from web https://app.simplelogin.io/ from here i can access via pc or phone always but when it comes to SimpleLogin app in android its timeout error!

**Comment by nguyenkims** [comment]
@IzumiSena oh that's indeed strange, do you know if the problem is persistent? If that's the case, can you send us your SimpleLogin email account at hi(at)simplelogin.io so we can investigate? Thanks and sorry for the issue!

**Comment by ntnhon** [comment]
Hello, a quick investigation shows that there is a bug that happens on the server side. The get aliases query takes more time than usual. We'll get back to you as soon as possible.
