### ISSUE TITLE
Simplify contact creation flow

### ISSUE THREAD

**Issue by ntnhon** [simple-login/Simple-Login-Android#39]
Tapping on an email address in other applications triggers SimpleLogin with 3 options: "Pick an alias", "Random an alias" & "Create an alias".

It would be simpler to just open a unique page which shows aliases and "Random an alias" & "Create an alias" as toolbar options.

**Comment by TheLastProject** [comment]
I would also really like it if the "Pick An Alias" screen (which will be a new page then) would have a search feature. With over 150 aliases, scrolling down to the right one in a randomly-ish sorted list is just impossible.

**Comment by ntnhon** [comment]
@TheLastProject Thank you for your suggestion! I finished implementing the search feature for "pick an alias" screen. I'll make an update today on Play Store and F-Droid.
https://github.com/simple-login/Simple-Login-Android/pull/54
