### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by shom13** [simple-login/Simple-Login-Android#4]
Firstly i would like to say, really great app, wonderful concept, yet so simple in design. Great work.

Couldnt find a community page, so i was wondering, if i wanted to add an alias to login to 2 or more websites, is it possible to mute or block one without blocking or disabling the whole alias.

**Comment by ntnhon** [comment]
Hi, thank you for your appreciation! We actually received similar requests from other users and we made a ticket for it which you can find in our roadmap on [Trello](https://trello.com/c/qvx1JGq6/74-able-to-block-a-specific-sender).

You can make more requests directly on Trello if you wish.

**Comment by ntnhon** [comment]
Hello, I created a discussion for this feature request in the app repository, it makes more sense there.
https://github.com/simple-login/app/discussions/406
