### ISSUE TITLE
User can delete their account

### ISSUE THREAD

**Issue by nguyenkims** [simple-login/Simple-Login-Android#41]
As this operation is sensible, user should confirm after re-entering the password.

The backend needs to provide an endpoint for deleting an account as well.

**Comment by ntnhon** [comment]
What if the user has 2FA enable?

**Comment by nguyenkims** [comment]
Oh that’s a good point. Maybe we can simply point user to the web app that’ll ask for 2FA code?

**Comment by ntnhon** [comment]
I think deleting an account is a destructive action. People usually don't do destructive things via mobile.
Other than that, such action requires an endpoint and again a destructive endpoint is not a great one. Too risky.
In my opinion it makes more sense to handle the deletion flow via web version.

**Comment by nguyenkims** [comment]
Yeah in this case, the delete button can simply a link to the settings page on the web version. We can use this link https://app.simplelogin.io/dashboard/setting#delete-account <https://app.simplelogin.io/dashboard/setting#delete-account>
