### ISSUE TITLE
Back nav button does not close/leave app at login screen

### ISSUE THREAD

**Issue by Pentaphon** [simple-login/Simple-Login-Android#45]
1) Install Simplelogin on a new device.
2) Open app, see login screen
3) Press the back button on your Android nav buttons. 
4) See that back button does absolutely nothing instead of closing/leaving the app as it should. 
5) Only ways to close/leave app app are to press the home button or recents button to go to another app. 

Happens on my brand new stock Android 10 phone and another person's Android 9 phone, so it's not a rom issue.

**Comment by ntnhon** [comment]
Hello, that's because I forgot to handle the back button event for this screen. Will have it fixed. Thank you for reporting!
