### ISSUE TITLE
Navigation buttons barely visible on light theme

### ISSUE THREAD

**Issue by Pentaphon** [simple-login/Simple-Login-Android#46]
This is on the stock Motorola ROM, Android 10.

Here's how the nav buttons look on Simplelogin on the light theme. You can just BARELY see them. 

![Screenshot_20210607-185716](https://user-images.githubusercontent.com/49374058/121111103-2cda8280-c7c3-11eb-9b42-2d76a5e09a51.png)

Here's how they look on another popular app with the light theme. You can easily see them. 

![Screenshot_20210607-185724](https://user-images.githubusercontent.com/49374058/121111162-3fed5280-c7c3-11eb-904f-36ef45342437.png)

**Comment by ntnhon** [comment]
Hello, thank you for reporting. I'll have a look and try to fix it!
