### ISSUE TITLE
Response error code 404

### ISSUE THREAD

**Issue by henkin67** [simple-login/Simple-Login-Android#47]
Hello,

I'm using the android app and correctly installed it.
I have sign in with my account and see the information.
But when I tried to create a new alias, I got the android message: response error code 404.
Through the web (chrome) on my Android phone everything is working well.

Do you have any ideas?

**Comment by ntnhon** [comment]
Hello, I just removed some old & unsecured endpoints several weeks ago. You might have an old version that still uses these deleted endpoints. Please try update the app and tell me if it works.

**Comment by henkin67** [comment]
Hello, on the android store I have the latest version (published the 25th of may).
Any other ideas?

**Comment by henkin67** [comment]
In addition here is the log:
2021-06-10 11:04:26,743 - sl - DEBUG - 10 - server:310 - after_request - 192.168.1.2 GET /api/v5/alias/options ImmutableMultiDict([]) 404

**Comment by ntnhon** [comment]
Are you self-hosting? Your IP address is a local one. That's probably the cause. If you're not interested in updating your SimpleLogin server, you can download the previous Android version from F-droid: https://f-droid.org/en/packages/io.simplelogin.android.fdroid/

**Comment by henkin67** [comment]
Yes I'm selfhosting it currently.
Does it means that the self-hosted version is not the last one?

**Comment by ntnhon** [comment]
That's right. Self-hosting for your private use may not be an issue but if you're sharing it with others, I recommend you to keep it up to date. So here are the solutions for your problem:
- Update your server.
- If you don't want to bother updating, you can build the app yourself using version 1.8: https://github.com/simple-login/Simple-Login-Android/releases
- If you don't have Android Studio installed, you can download the apk version 1.8 on F-droid: https://f-droid.org/en/packages/io.simplelogin.android.fdroid/
