### ISSUE TITLE
Option to delete alias on detail view of alias

### ISSUE THREAD

**Issue by parcelcat** [simple-login/Simple-Login-Android#57]
Currently, the only way to delete an alias is to swipe left on the alias entry in the list view of all of the aliases, then tap Delete. This isn't very discoverable, so it would be nice to see a delete button on the detail view of the alias as well.

**Comment by ntnhon** [comment]
Hello @parcelcat, sorry for the belated reply. I'll be working on redesigning the app and will take your suggestion into account 👍. I'll have an alias menu which has a delete button.

**Comment by ntnhon** [comment]
We'll work on a new design and make this option available in alias detail page.
