### ISSUE TITLE
Bug with the biometric authentication

### ISSUE THREAD

**Issue by ghost** [simple-login/Simple-Login-Android#66]
Hello,

I would like to report a bug with SimpleLogin for Android.
I have activated the biometric authentication for more security and it causes a bug.

Indeed, each time I launch the application, I have to put my fingerprint, which is normal.

If I cancel the biometric authentication (for example by clicking above the area asking me to enter my fingerprint), biometric authentication request closes and asks me to log in again (I have to put my email + password + 2FA).

Normally, it should just ask me for my fingerprint again because I was already logged in.
Also, it resets all SimpleLogin settings to default.

I use SimpleLogin for Android version 1.13.
I'm Android 9 with a Fairphone 3.

Could you please fix this ?

Regards,

**Comment by ntnhon** [comment]
Hello, thank you for reporting the the issue in detail. I'll investigate and get back to you soon.

**Comment by Anan-Saadi** [comment]
I am having the same issue

**Comment by brnl** [comment]
Any update on this @ntnhon?

I still have the same issue. Any failed finger print recognition directly logs me off _**and**_ wipes all my app settings. So one single misplaced finger might cause a lot of inconvenience.

I'm running the same version as OP, v1.13 from f-droid.

**Comment by FOM333** [comment]
This issue is still present for me in version 1.16.0.

**Comment by ntnhon** [comment]
Hello, this should be fixed in version 1.18.0
