### ISSUE TITLE
alias counter (forwards, replies and blocks) set to 0 (need to refresh)

### ISSUE THREAD

**Issue by Spitfireap** [simple-login/Simple-Login-Android#75]
Hi,

I've updated my own instance to 4.6.2-beta and after the upgrade all alias counter on the app have been reset to 0 (per alias) 
![Screenshot_20220623-181347_SimpleLogin](https://user-images.githubusercontent.com/45575529/175346934-f31f66b3-7b58-4d09-ab19-f3b3f462cffc.jpg)

If I go to the alias detail, counters are still at 0 but transited emails are shown. 
![Screenshot_20220623-181414_SimpleLogin](https://user-images.githubusercontent.com/45575529/175347243-8a067355-512b-4be4-8cca-f10b86baac8c.jpg)

After refreshing from here (swiping up), counters get updated and everything is back to normal for *this* alias. And change is kept even after reseting the app. It seems it may be more on db side ?

**Comment by nguyenkims** [comment]
For now I don't have any idea as refreshing seems to solve the issue as the server doesn't use any cache. Can you check in the server log if you see any error?

**Comment by Spitfireap** [comment]
> For now I don't have any idea as refreshing seems to solve the issue as the server doesn't use any cache. Can you check in the server log if you see any error?

ok found it (kind of). [get_aliases()](https://github.com/simple-login/app/blob/de31e6d07294d1dc2443069551be99c1c6887ce4/app/api/views/alias.py#L33) returns me the right number, but [get_alias_v2](https://github.com/simple-login/app/blob/de31e6d07294d1dc2443069551be99c1c6887ce4/app/api/views/alias.py#L75) returns me 0 on nb_block, nb_forward, etc. After refreshing the app it must update the db, by getting alias through v1 ? I'm not good enough in db stuff to completly understand the table/research you have :)

**Comment by nguyenkims** [comment]
The difference between `get_alias` and `get_alias_v2` is the former uses `get_alias_infos_with_pagination()` whereas the latter uses `get_alias_infos_with_pagination_v3` which is also used by the web. Do you see the same issue (i.e. 0 counter) on the web dashboard?

**Comment by Spitfireap** [comment]
Yes same happens on the web. On global alias page counter are wrong but on individual alias detail (/dashboard/alias_log/X) it is the right number

**Comment by nguyenkims** [comment]
@Spitfireap do you mean the counter here is wrong? 

![image](https://user-images.githubusercontent.com/3167780/177006369-ef9bc0ba-f5cd-49a0-96f1-aa7740c64c3a.png)

but the one here is correct? 

![image](https://user-images.githubusercontent.com/3167780/177006377-089febe8-f61e-4007-8bad-f67f2c7c28ab.png)

**Comment by nguyenkims** [comment]
Do you mean this one here is wrong? 
![image](https://user-images.githubusercontent.com/3167780/177006406-f2398f38-f5b4-45ad-ad8f-aee0c6a04425.png)

but the one here is correct?

![image](https://user-images.githubusercontent.com/3167780/177006421-35b00900-cd51-41ae-be8e-a68af028fa03.png)

**Comment by Spitfireap** [comment]
Exactly. Does it thinks email handled in 3.4.0 are more than 2 weeks old ? 
Anyway so much research for this small issue is maybe overkill :)

**Comment by nguyenkims** [comment]
@Spitfireap that's my only hypothesis for now. Let's see in 2 weeks if this issue magically goes away :)
