### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Beventar** [simple-login/Simple-Login-Android#77]
I think the "Aliases" and "Mailboxes" menus in the hamburger menu should be at the bottom of the screen like the Play Store app or AnonAddy app or Sync for reddit beta and many others.

This would increase visibility and make it easier to navigate the app and be prettier than the solution we have now.

My 2nd suggestion is to remove the hamburger menu entirely:

![simplelogin mobile app ui overhaul](https://user-images.githubusercontent.com/51784467/176133235-267acd13-7b01-4fac-9ff1-d0ed49b9093e.png)

An artistic representation made in paint here.

Or just the same UI that's on iOS could be recreated on Android.

**Comment by ntnhon** [comment]
Hello, we plan to work on redesigning the app and we'll use tabs like what you're proposing. The work is pretty much done for iOS but for Android it'll take some time. Here are some screenshots from the iOS version.
![image](https://user-images.githubusercontent.com/4153453/176139344-cd8ab1b8-aa89-479b-ae91-3978c863e722.png)
![image](https://user-images.githubusercontent.com/4153453/176139359-0aae18b1-09b5-4e26-839f-d11371a1ab04.png)
![image](https://user-images.githubusercontent.com/4153453/176139391-6954cb9d-18c2-4378-a147-6e2f9195eb74.png)
![image](https://user-images.githubusercontent.com/4153453/176139427-d7a14d2e-7c98-4734-a4f4-825e32b20bf1.png)
![image](https://user-images.githubusercontent.com/4153453/176139471-f9cbbb2b-6daa-4fd0-a60d-a971880ab74d.png)
![image](https://user-images.githubusercontent.com/4153453/176139499-fa9dcd37-0adb-47f0-8acb-01209baedfdb.png)
![image](https://user-images.githubusercontent.com/4153453/176139532-694d00bb-d474-4360-bf5f-9b292259e92c.png)

**Comment by ntnhon** [comment]
You're most welcome. If you happen to have iOS devices and want to check out this new version which is still in beta. Please let me know :)

**Comment by Beventar** [comment]
Hey I actually do have an iOS device now and I'd love to test the new app out.
Is the beta app stable enough for normal day to day usage etc.?

**Comment by ntnhon** [comment]
Hello, yes it's pretty stable I'd say. You can install it via this link: https://testflight.apple.com/join/atEnn7SL
