### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by Nextross** [simple-login/Simple-Login-Android#9]
I've been using SimpleLogin for around a month, but when I wanted to create new alias, the app showed an error message. I tried reinstalling the app, but the the problem is still there.
![Screenshot_20201206_102634_io simplelogin android fdroid_1](https://user-images.githubusercontent.com/70912486/101276546-05701200-37ae-11eb-8eed-019563f566fa.jpg)

**Comment by nguyenkims** [comment]
Hi due to a DNS issue, our api isn't accessible during 2.5 hours today. This issue has been solved now, sorry for the problem!
