### ISSUE TITLE
Bug - nothing happen when opening mailto link

### ISSUE THREAD

**Issue by fryorcraken** [simple-login/Simple-Login-Android#95]
1. on a mailto link in Firefox
2. Select simple login in android app selection menu
3. Simple login opens with no action in regards to the email

Expected: an action menu similar to the one I get when I open an email from the contacts app.

**Comment by fryorcraken** [comment]
I would imagine a similar flow to the "send" flow from an alias. With an added first step to select the alias to send from

**Comment by nguyenkims** [comment]
@fryorcraken that's indeed a good idea. Can you please create a feature request on our forum at https://github.com/simple-login/app/discussions so other people can upvote it?

**Comment by fryorcraken** [comment]
Done https://github.com/simple-login/app/discussions/1382
