### ISSUE TITLE
Limited Display of Reverse Aliases List (Contact List for Alias)

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [simple-login/Simple-Login-Android#98]
In the android app, after choosing "Send Email" for an alias, the list of contacts seems to be limited to showing 20 contacts and does not expand to show more like scrolling through the aliases does.  I ran into an issue where I wanted to reply through a certain alias that has many existing contact and I didn't see the contact that I needed in the initial 20 contacts, so I tried to create that contact.  However, the contact I wanted to reply to already existed and could not be recreated for that alias, but I couldn't scroll through the many contacts I had for that alias to find the specific contact.  Would it be possible to allow that list to load additional contacts like the list of aliases can load additional existing aliases?

Great job on the app, everyone!

**Comment by ntnhon** [comment]
Hello, this is fixed and under Play Store review. Should be available soon. Thanks for your report.

**Comment by shrimprugbysnowowl** [comment]
Cool, thank you!
